In [1]:
# ============================================================
# DESAFÍO 3
# Autor: Catalina Ormeño Rivera
# Fecha: 23/10/2025
# Archivo: desafio3.ipynb
# ============================================================

# Importar Librería necesaria
import pandas as pd
# Cargar archivo original de transacciones (transacciones.txt)
df = pd.read_csv("transacciones.txt", sep="|")

# Mostrar las primeras filas para ver estructura
print("Datos originales:")
display(df.head())


# Separar la columna compuesta 'canal_venta'
# Esta columna tiene dos valores separados por espacio (canal + sucursal)
df[['canal', 'sucursal']] = df['canal_venta'].str.split(' ', expand=True)

# 4Reemplazar los códigos por nombres legibles
df['canal'] = df['canal'].map({'CtoCcCl': 'Call Center Cliente'})
df['sucursal'] = df['sucursal'].map({'CTOMA': 'Sucursal Toma'})


# Eliminar columna original y limpiar datos
df = df.drop(columns=['canal_venta'])

# Mostrar resultado limpio
print("Datos transformados:")
display(df.head())

# Exportar el dataframe limpio a CSV
df.to_csv("transacciones_clean.csv", index=False)
print("Archivo limpio exportado como 'transacciones_clean.csv'")

# Demostración final
print(f"Total de registros procesados: {len(df)}")
print(f"Columnas finales: {list(df.columns)}")

Datos originales:

,IdCliente,fecha_compra,cantidad_articulos,monto_transaccion_clp,Id_medio_de_pago,nombre_cliente,canal_venta
0,5362825,16-07-2021,4,6520,2,HUGO VARGAS SOTO,CtoCcCl CTOMA
1,5362825,11-08-2021,6,8915,2,HUGO VARGAS SOTO,CtoCcCl CTOMA
2,5362825,16-07-2021,12,25660,2,HUGO VARGAS SOTO,CtoCcCl CTOMA
3,5362825,16-06-2021,8,6400,3,HUGO VARGAS SOTO,CtoCcCl CTOMA
4,5362825,16-07-2021,5,9205,2,HUGO VARGAS SOTO,CtoCcCl CTOMA

Datos transformados:

,IdCliente,fecha_compra,cantidad_articulos,monto_transaccion_clp,Id_medio_de_pago,nombre_cliente,canal,sucursal
0,5362825,16-07-2021,4,6520,2,HUGO VARGAS SOTO,Call Center Cliente,Sucursal Toma
1,5362825,11-08-2021,6,8915,2,HUGO VARGAS SOTO,Call Center Cliente,Sucursal Toma
2,5362825,16-07-2021,12,25660,2,HUGO VARGAS SOTO,Call Center Cliente,Sucursal Toma
3,5362825,16-06-2021,8,6400,3,HUGO VARGAS SOTO,Call Center Cliente,Sucursal Toma
4,5362825,16-07-2021,5,9205,2,HUGO VARGAS SOTO,Call Center Cliente,Sucursal Toma

Archivo limpio exportado como 'transacciones_clean.csv'
Total de registros procesados: 13
Columnas finales: ['IdCliente', 'fecha_compra', 'cantidad_articulos', 'monto_transaccion_clp', 'Id_medio_de_pago', 'nombre_cliente', 'canal', 'sucursal']